config/routes.rb
Rails.application.routes.draw do
  root to: "airplanes#index"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :airplanes do
    resources :bookings, only: %i[create]
  end
  # Defines the root path route ("/")
  # root "articles#index"
  get 'search', to: 'airplanes#search'
  get 'dashboard', to: 'pages#dashboard'
end

app/models/airplane.rb
class Airplane < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos

  validates :weight, presence: true, comparison: { greater_than: 0 }
  validates :registration, presence: true
  validates :number_of_engines, presence: true
  validates :brand_and_model, presence: true
  validates :pax_capacity, presence: true
  validates :range, presence: true
  validates :speed, presence: true
  validates :max_altitude, presence: true
  validates :address, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_brand_and_model,
  against: [ :brand_and_model ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :airplane
  validates :start_day, presence: true
  validates :end_day, presence: true, comparison: { greater_than: :start_day }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :airplanes
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  before_action :set_airplane, only: [:show, :edit, :update, :destroy]
  before_action :check_if_can_access, only: [:edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :search]


  def index
    @airplanes = Airplane.all
    @markers = @airplanes.geocoded.map do |airplane|
      {
        lat: airplane.latitude,
        lng: airplane.longitude
      }
    end
  end

  def show
    @booking = Booking.new
    @marker = [ {lng: @airplane.longitude, lat: @airplane.latitude} ]
  end

  def new
    @airplane = Airplane.new
  end

  def create
    @airplane = Airplane.new(airplane_params)
    @airplane.user = current_user
    if @airplane.save
      attach_photos
      redirect_to airplane_path(@airplane)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @airplane.update(airplane_params)
      attach_photos
      redirect_to airplane_path(@airplane)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @airplane.destroy
    redirect_to airplanes_path, status: :see_other
  end

  def search
    @airplanes = Airplane.search_by_brand_and_model(params[:brand])
    render :index
  end

  private

  def check_if_can_access
    if @airplane.user != current_user
      redirect_to root_path, notice: "You're not allowed to edit or delete an airplane if you're not the owner!"
    end
  end

  def airplane_params
    params.require(:airplane).permit(:weight, :registration, :number_of_engines, :brand_and_model, :pax_capacity, :speed, :range, :max_altitude, :address)
  end

  def set_airplane
    @airplane = Airplane.find(params[:id])
  end

  def attach_photos
    # :photos were consciously removed from airplane_params and attachments are handled explicitly.
    # The default behavior as of Rails 7 is to replace existing attachments on update while we want
    # to keep existing files and append new photos if any.
    #
    # Workaround as per
    # https://stackoverflow.com/questions/71990425/rails-active-storage-keep-existing-files-uploads
    @airplane.photos.attach(params[:airplane][:photos]) if params.dig(:airplane, :photos).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @airplane = Airplane.find(params[:airplane_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.airplane = @airplane
    if valid_interval?(check_intervals(@booking))
      if @booking.save
        redirect_to airplane_path(@airplane), notice: "Booking successfully saved"
      else
        render "airplanes/show", status: :unprocessable_entity
      end
    else
      flash[:alert] = "Dates not available"
      render "airplanes/show", status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_day, :end_day)
  end

  def check_intervals(booking_airplane)
    airplane = Airplane.find(params[:airplane_id])
    bookings = Booking.where(airplane:)
    check_array = []
    bookings.each do |booking|
      if (booking.start_day..booking.end_day).cover?(booking_airplane.start_day) || (booking.start_day..booking.end_day).cover?(booking_airplane.end_day)
        check_array << false
      else
        check_array << true
      end
    end
    check_array
  end

  def valid_interval?(check_array)
    !check_array.include?(false)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def dashboard
    @airplanes_user = Airplane.where(user_id: current_user)
    @bookings = Booking.where(user_id: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/airplanes/_form.html.erb
<%= simple_form_for(airplane, data: {turbo: false}) do |f| %>
  <%= f.input :brand_and_model, placeholder:'Brand and model', label: false %>
  <%= f.input :registration, placeholder:'Registration', label: false %>
  <%= f.input :weight, placeholder:'Weight', label: false %>
  <%= f.input :range, placeholder:'Range', label: false %>
  <%= f.input :speed, placeholder:'Speed', label: false %>
  <%= f.input :number_of_engines, placeholder:'Number of engines', label: false %>
  <%= f.input :pax_capacity, placeholder:'Pax capacity', label: false %>
  <%= f.input :max_altitude, placeholder:'Max altitude', label: false %>
  <%= f.input :address, placeholder:'Address', label: false %>
  <%= f.input :photos, as: :file, input_html: { multiple: true }, placeholder:'Brand and model', label: false %>
  <%= f.submit "Submit", class: "btn btn-gradient" %>
<% end %>

app/views/airplanes/edit.html.erb
<h2>Edit airplane</h2>
<div class="container">
  <%= render "form", airplane: @airplane %>
  <%= link_to "Return", airplane_path(@airplane.id), class: "btn btn-gradient" %>
</div>

app/views/airplanes/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://compareprivateplanes.com/images/gulfstream/g700/16.jpeg);">
  <div class="container">
    <h1><strong>Touch</strong> & <strong>Go</strong>!</h1>
    <p>Rent aircrafts and crews</p>
    <a class="btn btn-banner" href="#">Start up Checklist</a>
  </div>
  <p class="credits">Copyrights courtesy of Gulfstream Aerospace Corporation </p>
</div>
<div class="containerhome">
  <% if @airplanes != [] %>
    <div class="homegrid">
      <% @airplanes.each do |airplane| %>
        <div class="col">
          <div class="card">
            <div class="card-body">
              <% unless airplane.photos.first.nil? %>
                <%= cl_image_tag airplane.photos.first.key, class:"card-img-top" %>
              <% end %>
              <h5 class="card-title"> <%= airplane.brand_and_model %></h5>
              <p class="card-list"> <%= airplane.registration %></p>
              <p> <%= airplane.user.first_name %> <%=  airplane.user.last_name %>
                <%= link_to "More infos about that plane", airplane_path(airplane.id) %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <h3>No airplanes available yet ...</h3>
  <% end %>
</div>

app/views/airplanes/new.html.erb
<div class="container">
  <h2> You can now add a new airplane ! </h2>
  <%= render "form", airplane: @airplane %>
  <%= link_to "Return", airplanes_path, class: "btn btn-gradient" %>
</div>

app/views/airplanes/show.html.erb
<div class="container">
  <div class="container-carousel">
    <div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <% @airplane.photos.each_with_index do |photo, index| %>
          <% active = index == 0 ? "active" : "" %>
          <div class="carousel-item <%= active %>" data-bs-interval="10000">
            <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill , class:"d-block" %>
            <div class="carousel-caption d-none d-md-block">
              <h2 class="light-text shadow-text">Amazing</h2>
              <h3 class="light-text shadow-text"><%= @airplane.brand_and_model %></h3>
            </div>
          </div>
        <% end %>
      </div>
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
  <div class="container-button">
    <%= link_to "Delete",
    airplane_path(@airplane),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
    class: "btn btn-gradient"%>
    <%= link_to "Back", airplanes_path, class: "btn btn-gradient", id:"middle-button" %>
    <%= link_to "Edit", edit_airplane_path(@airplane.id), class: "btn btn-gradient" %>
  </div>
  <div class="container-text">
    <h1>You can now book this plane!</h1>
  </div>
  <div class="container-map-booking">
    <div class="container-map" style="width: 600px; height: 300px;"
     data-controller="map"
     data-map-markers-value="<%= @marker.to_json %>"
     data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
    <div class="container-booking">
      <%= render "bookings/form", airplane: @airplane, booking: @booking %>
    </div>
  </div>
</div>

app/views/bookings/_form.html.erb
<%= simple_form_for [airplane, booking] do |f| %>
  <%= f.input :start_day, as: :string, input_html: { data: { controller: "flatpickr" } } %>
  <%= f.input :end_day, as: :string, input_html: { data: { controller: "flatpickr" } } %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TouchAndGo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/8c1b4cb35e.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>
  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon" class="border border-success p-2 mb-2">
      <div class="container-fluid">
        <%= link_to airplanes_path, class: "navbar-brand" do %>
          <i class="fa-solid fa-plane-departure"></i>
          <% unless current_page?(root_path) %>
            <p> Touch and go </p>
          <% end %>
        <% end %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%# search bar %>
        <form class="form-inline d-flex" action="<%= search_path %>">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="brand">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <% if user_signed_in? %>
              <li class="nav-item active">
                <%= link_to "Home", airplanes_path, class: "nav-link" %>
              </li>
              <li class="nav-item dropdown">
                <%= image_tag "https://images.pexels.com/photos/40753/military-raptor-jet-f-22-airplane-40753.jpeg?auto=compress&cs=tinysrgb&w=800", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <%= link_to "Dashboard", "/dashboard", class: "dropdown-item" %>
                  <%= link_to "Add a new plane", new_airplane_path, class: "dropdown-item" %>
                  <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
                </div>
              </li>
            <% else %>
              <li class="nav-item"-->
                <%= link_to "Login", new_user_session_path, class: "nav-link" %>
              </li-->
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="main-container">
      <%= yield %>
      <%= render "shared/flashes" %>
    </div>

    <div class="footer">
      <div class="footer-links">
        <a href="https://github.com"><i class="fab fa-github"></i></a>
        <a href="https://www.instagram.com"><i class="fab fa-instagram"></i></a>
        <a href="https://www.facebook.com"><i class="fab fa-facebook"></i></a>
        <a href="https://twitter.com"><i class="fab fa-twitter"></i></a>
        <a href="https://www.linkedin.com"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
        This footer is made with <i class="fas fa-heart"></i> Touch and Go
      </div>
    </div>
  </body>
</html>

app/views/pages/_my_bookings.html.erb
<div class="homegrid">
  <% @bookings.each do |booking| %>
    <div class="col">
      <div class="card">
        <div class="card-body">
          <% unless booking.airplane.photos.first.nil? %>
            <%= cl_image_tag booking.airplane.photos.first.key, class: "card-img-top" %>
          <% end %>
          <h5 class="card-title"> <%= booking.airplane.brand_and_model %></h5>
          <p class="card-list"> <%= booking.airplane.registration %></p>
          <p> <%= booking.user.first_name %> <%= booking.user.last_name %></p>
          <%= link_to "Display", airplane_path(booking.airplane) %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/_my_planes.html.erb
<div class="homegrid">
  <% @airplanes_user.each do |airplane| %>
    <div class="col">
      <div class="card">
        <div class="card-body">
          <% unless airplane.photos.first.nil? %>
            <%= cl_image_tag airplane.photos.first.key, class: "card-img-top" %>
          <% end %>
          <h5 class="card-title"> <%= airplane.brand_and_model %></h5>
          <p class="card-list"> <%= airplane.registration %></p>
          <p> <%= airplane.user.first_name %> <%= airplane.user.last_name %></p>
          <% if @bookings.include?(Booking.where(airplane_id: airplane.id).first) %>
            <span>Booked</span>
          <% else %>
            <span>Available</span>
          <% end %>
          <%= link_to "Display", airplane_path(airplane.id) %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/dashboard.html.erb
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true">My airplanes</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false">My bookings</button>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0">
    <%= render "my_planes" %>
  </div>
  <div class="tab-pane fade" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">
    <%= render "my_bookings" %>
  </div>
</div>

app/views/pages/show.html.erb
<%# <h3><%=@airplane.brand_and_model%></h3>

<%# <% @article.photos.each do |photo| %>
<%#   <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
<%# <% end %>

<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="10000">
      <img src="..." class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>First slide label</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
    <div class="carousel-item" data-bs-interval="2000">
      <img src="..." class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Second slide label</h5>
        <p>Some representative placeholder content for the second slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Third slide label</h5>
        <p>Some representative placeholder content for the third slide.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>


<%= render "form", airplane: @airplane %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>